spring:
  mvc:
    favicon:
      enabled: false
  favicon:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    net:
      ludeo:
        recikligi: DEBUG

recikligi:
  storageFolder: /tmp
  watson:
    apikey:
  score:
    threshold:
      high: 80
      medium: 60
  daily:
    usage:
      limit: 100
  image:
    resize:
      display:
        width: 1024
      recognition:
        width-or-height: 2048